import { storage, db } from '../lib/firebase'
import { getDownloadURL, listAll, ref } from 'firebase/storage'
import { collection, DocumentData, getDocs } from 'firebase/firestore'
import Head from 'next/head'
import Hero from '../components/landing-page/Hero'
import Introduction from '../components/landing-page/Introduction'

interface Props {
  heroImageUrls: string[]
  introductionDocs: DocumentData[]
}

export default function Home ({ heroImageUrls, introductionDocs }: Props) {
  return (
    <>
      <Head>
        <title>Sejong Taekwondo</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.png"/>
      </Head>
      <Hero heroImages={heroImageUrls}/>
      <Introduction slidesData={introductionDocs}/>
    </>
  )
}

export async function getStaticProps () {
  const heroImagesFolderHref = ref(storage, 'images/hero')
  let heroImageUrls = []
  let introductionDocs: DocumentData[] = []

  try {
    const heroImageRefs = (await listAll(heroImagesFolderHref)).items

    const heroImageUrlPromises = heroImageRefs.map(async ref => {
      return await getDownloadURL(ref)
    })

    for await (let heroImageUrl of heroImageUrlPromises) {
      heroImageUrls.push(heroImageUrl)
    }
  } catch (e) {
    console.log(e)
  }

  const querySnapshot = await getDocs(collection(db, 'who-are-we'))
  querySnapshot.forEach(doc => {
    introductionDocs.push({id: doc.id, ...doc.data()})
  })

  return {
    props: {
      heroImageUrls,
      introductionDocs
    }
  }
}
